config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: 'users',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :administrators,
             path: 'administrators',
             controllers: {
               sessions: 'administrators/sessions'
             }

  namespace :admin do
    resources :administrators
    resources :hubs
    root to: 'administrators#index'
  end

  namespace :hubby do
    get 'dashboard', to: 'dashboard#index'
    resources :users
    root to: 'dashboard#index'
  end

  root to: redirect('/hubby/dashboard')
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable

  validates :email, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hub.rb
# == Schema Information
#
# Table name: hubs
#
#  id   :integer          not null, primary key
#  name :string
#

class Hub < ApplicationRecord
  has_many :users

  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  hub_id                 :integer
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable

  belongs_to :hub

  validates :email, presence: true
end

app/controllers/admin/administrators_controller.rb
module Admin
  class AdministratorsController < Admin::BaseController
    def index
      @administrators = Administrator.all
    end

    def new
      @administrator = Administrator.new
    end

    def create
      @administrator = Administrator.new(administrator_params)
      if @administrator.invite!
        redirect_to(
          admin_administrators_path,
          notice: "L'administrateur a été ajouté."
        )
      else
        render :new
      end
    end

    def edit
      @administrator = Administrator.find(params[:id])
    end

    def update
      @administrator = Administrator.find(params[:id])
      if @administrator.update_attributes(administrator_params)
        redirect_to(
          admin_administrators_path,
          notice: "L'administrateur a été mis à jour."
        )
      else
        render :edit
      end
    end

    def destroy
      @administrator = Administrator.find(params[:id])
      if @administrator.destroy
        redirect_to(
          admin_administrators_path,
          notice: "L'administrateur a été supprimé."
        )
      else
        redirect_to(
          admin_administrators_path,
          alert: "L'administrateur n'a pas été supprimé."
        )
      end
    end

    private

    def administrator_params
      params.require(:administrator).permit(
        :email
      )
    end
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_action :authenticate_administrator!

    layout :layout_by_resource

    protected

    def layout_by_resource
      devise_controller? ? 'admin/public' : 'admin/authorized'
    end
  end
end

app/controllers/admin/hubs_controller.rb
module Admin
  class HubsController < Admin::BaseController
    def index
      @hubs = Hub.all
    end

    def new
      @hub = Hub.new
    end

    def create
      @hub = Hub.new(hub_params)
      if @hub.save
        redirect_to(
          admin_hubs_path,
          notice: "L'initiative a été créée."
        )
      else
        render :new
      end
    end

    def edit
      @hub = Hub.find(params[:id])
    end

    def update
      @hub = Hub.find(params[:id])
      if @hub.update_attributes(hub_params)
        redirect_to(
          admin_hubs_path,
          notice: "L'initiative a été mise à jour."
        )
      else
        render :edit
      end
    end

    def destroy
      @hub = Hub.find(params[:id])
      if @hub.destroy
        redirect_to(
          admin_hubs_path,
          notice: "L'initiative a été supprimée."
        )
      else
        redirect_to(
          admin_hubs_path,
          alert: "L'initiative n'a pas été supprimée."
        )
      end
    end

    private

    def hub_params
      params.require(:hub).permit(
        :name
      )
    end
  end
end

app/controllers/administrators/sessions_controller.rb
class Administrators::SessionsController < Devise::SessionsController
  layout 'admin/public'

  protected

  def after_sign_out_path_for(resource)
    admin_root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'hubby/public'

  before_action :set_locale

  protected

  def set_locale
    I18n.locale = I18n.default_locale
  end
end

app/controllers/hubby/base_controller.rb
module Hubby
  class BaseController < ApplicationController
    before_action :authenticate_user!

    layout :layout_by_resource

    def current_hub
      current_user.hub
    end
    helper_method :current_hub

    protected

    def layout_by_resource
      devise_controller? ? 'hubby/public' : 'hubby/authorized'
    end
  end
end

app/controllers/hubby/dashboard_controller.rb
module Hubby
  class DashboardController < Hubby::BaseController
    def index

    end
  end
end

app/controllers/hubby/users_controller.rb
module Hubby
  class UsersController < Hubby::BaseController
    def index
      @users = current_hub.users.all
    end

    def new
      @user = current_hub.users.new
    end

    def create
      @user = current_hub.users.new(user_params)
      if @user.save
        redirect_to(
          hubby_users_path,
          notice: "L'accès du membre a été créé."
        )
      else
        render :new
      end
    end

    def edit
      @user = current_hub.users.find(params[:id])
    end

    def update
      @user = current_hub.users.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to(
          hubby_users_path,
          notice: "L'accès du membre a été mis à jour."
        )
      else
        render :edit
      end
    end

    def destroy
      @user = current_hub.users.find(params[:id])
      if @user.destroy
        redirect_to(
          hubby_users_path,
          notice: "L'accès du membre a été supprimé."
        )
      else
        redirect_to(
          hubby_users_path,
          alert: "L'accès du membre n'a pas pu être supprimé."
        )
      end
    end

    private

    def user_params
      params.require(:user).permit(
        :email,
        :password,
        :password_confirmation
      )
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def no_data(text)
    content_tag(:div, text, class: 'warning callout')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/administrators/_administrator.html.slim
p
  => link_to administrator.email, edit_admin_administrator_path(administrator)
  - if !administrator.invitation_accepted?
    span.secondary.label invité

app/views/admin/administrators/_form.html.slim
= f.input :email

app/views/admin/administrators/_sidebar.html.slim
= link_to 'Inviter un administrateur', new_admin_administrator_path, class: 'button'

app/views/admin/administrators/edit.html.slim
= simple_form_for @administrator, url: admin_administrator_path(@administrator) do |f|
  = render 'form', f: f

  = f.button :submit, 'Enregistrer', class: 'primary button'

app/views/admin/administrators/index.html.slim
- content_for :sidebar do
  = render 'sidebar'

- if @administrators.any?
  = render @administrators
- else
  = no_data("Aucun administrateur enregistré.")

app/views/admin/administrators/new.html.slim
- content_for :sidebar do
  = render 'sidebar'

= simple_form_for @administrator, url: admin_administrators_path do |f|
  = render 'form', f: f

  = f.button :submit, 'Enregistrer', class: 'success button'

app/views/admin/hubs/_form.html.slim
= f.error_notification

= f.input :name

app/views/admin/hubs/_hub.html.slim
p
  = link_to hub.name, edit_admin_hub_path(hub)

app/views/admin/hubs/_sidebar.html.slim
= link_to 'Ajouter une initiative', new_admin_hub_path, class: 'button'

app/views/admin/hubs/edit.html.slim
= simple_form_for @hub, url: admin_hub_path(@hub) do |f|
  = render 'form', f: f

  = f.button :submit, 'Enregistrer', class: 'primary'

app/views/admin/hubs/index.html.slim
- content_for :sidebar do
  = render 'sidebar'

- if @hubs.any?
  = render @hubs
- else
  = no_data("Aucune initiative enregistrée.")

app/views/admin/hubs/new.html.slim
= simple_form_for @hub, url: admin_hubs_path do |f|
  = render 'form', f: f

  = f.button :submit, 'Enregistrer', class: 'success'

app/views/administrators/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, t("devise.invitations.edit.submit_button") %>
<% end %>

app/views/administrators/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <%= f.input field %>
<% end -%>

<%= f.button :submit, t("devise.invitations.new.submit_button") %>
<% end %>

app/views/hubby/dashboard/index.html.slim
| Hello world.

app/views/hubby/users/_actions.html.slim
= link_to 'Ajouter un membre', new_hubby_user_path, class: 'button'

app/views/hubby/users/_form.html.slim
= f.input :email, label: 'Adresse email'
= f.input :password, label: 'Mot de passe'
= f.input :password_confirmation, label: 'Confirmation du mot de passe'

app/views/hubby/users/_user.html.slim
p = link_to user.email, edit_hubby_user_path(user)

app/views/hubby/users/edit.html.slim
- content_for :title, 'Membres'

= simple_form_for @user, url: hubby_user_path(@user) do |f|
  = render 'form', f: f

  = f.button :submit, 'Enregistrer', class: 'primary'

app/views/hubby/users/index.html.slim
- content_for :title, 'Membres'
- content_for :actions, render('actions')

- if @users.any?
  = render @users
- else
  = no_data("Aucun membre enregistré.")

app/views/hubby/users/new.html.slim
- content_for :title, 'Membres'

= simple_form_for @user, url: hubby_users_path do |f|
  = render 'form', f: f

  = f.button :submit, 'Enregistrer', class: 'success'

app/views/layouts/admin/authorized.html.slim
doctype html
html(lang="fr")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title = yield :head_title
    = stylesheet_link_tag 'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    = yield :head
  body
    .top-bar
      .top-bar-left
        ul.dropdown.menu(data-dropdown-menu)
          li.menu-text TransitionApp
          li(class="#{controller_name == 'hubs' ? 'active' : nil}")
            = link_to 'Initiatives', admin_hubs_path
          li(class="#{controller_name == 'administrators' ? 'active' : nil}")
            = link_to 'Administrateurs', admin_administrators_path
      .top-bar-right
        ul.menu
          li
            = link_to 'Me déconnecter', \
                      destroy_administrator_session_path, \
                      method: :delete

    #admin
      .container
        .row
          .small-12.medium-3.columns
            #sidebar
              = yield :sidebar
          .small-12.medium-9.columns
            #content
              = render 'layouts/admin/shared/messages'

              = yield

app/views/layouts/admin/public.html.slim
doctype html
html(lang="fr")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title = yield :head_title
    = stylesheet_link_tag 'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    = yield :head
  body
    .container
      .row
        .small-12.medium-6.large-4.medium-offset-3.large-offset-4.columns
          h1 TransitionApp Admin

          = render 'layouts/admin/shared/messages'
          = yield

app/views/layouts/admin/shared/_messages.html.slim
- if flash.any?
  #messages
    - flash.each do |name, msg|
      - if msg.class == Array
        - msg.compact.each do |message|
          div(class="#{name.to_s == "notice" ? "success" : "alert"} callout" data-closable)
            button.close-button(aria-label="Dismiss alert" type="button" data-close)
              span(aria-hidden="true") &times;
            = content_tag :div, message, id: "flash_#{name}"
      - elsif !msg.nil?
          div(class="#{name.to_s == "notice" ? "success" : "alert"} callout" data-closable)
            button.close-button(aria-label="Dismiss alert" type="button" data-close)
              span(aria-hidden="true") &times;
            = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/hubby/authorized.html.slim
doctype html
html(lang="#{I18n.locale}")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title = yield :head_title
    = stylesheet_link_tag 'hubby', media: 'all'
    = javascript_include_tag 'hubby'
    = csrf_meta_tags
    = yield :head
  body
    #header
      .container
        .row.collapse.align-middle
          .small-3.columns
            #logo
              strong TransitionApp
              div Mon initiative de transition en ligne
          .small-9.columns
            #desk.bigger
              = current_hub.name
    #main
      .container
        .row.collapse
          .small-3.columns
            #sidebar
              ul.vertical.menu
                li(class="#{controller_name == 'dashboard' ? 'active' : nil}")
                  = link_to 'Tableau de bord', hubby_dashboard_path
                li
                  = link_to destroy_user_session_path, method: :delete do
                    .text-muted
                      i.fa.fa-fw.fa-sign-out
                      |  Me déconnecter

              - if current_user.manager
                hr
                h5 Gestion

                ul.vertical.menu
                  li(class="#{controller_name == 'users' ? 'active' : nil}")
                    = link_to 'Membres', hubby_users_path

          .small-9.columns
            #content
              #content-header
                .row.align-middle
                  .columns
                    h1 = yield :title
                  .shrink.columns
                    = yield :actions

              = render "layouts/hubby/shared/messages"
              = yield

            #footer

app/views/layouts/hubby/public.html.slim
doctype html
html(lang="#{I18n.locale}")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title = yield :head_title
    = stylesheet_link_tag 'hubby', media: 'all'
    = javascript_include_tag 'hubby'
    = csrf_meta_tags
    = yield :head
  body
    .container
      .row
        .small-12.medium-6.large-4.medium-offset-3.large-offset-4.columns
          h1 TransitionApp

          = render 'layouts/hubby/shared/messages'
          = yield

app/views/layouts/hubby/shared/_messages.html.slim
- if flash.any?
  #messages
    - flash.each do |name, msg|
      - if msg.class == Array
        - msg.compact.each do |message|
          div(class="#{name.to_s == "notice" ? "success" : "alert"} callout" data-closable)
            / button.close-button(aria-label="Dismiss alert" type="button" data-close)
            /   span(aria-hidden="true") &times;
            = content_tag :div, message, id: "flash_#{name}"
      - elsif !msg.nil?
          div(class="#{name.to_s == "notice" ? "success" : "alert"} callout" data-closable)
            / button.close-button(aria-label="Dismiss alert" type="button" data-close)
            /   span(aria-hidden="true") &times;
            = content_tag :div, msg, id: "flash_#{name}"

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Me connecter", new_session_path(resource_name)
  br

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "M'inscrire", new_registration_path(resource_name)
  br

- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "J'ai oublié mon mot de passe", new_password_path(resource_name)
  br

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Vous n'avez pas reçu les instructions pour confirmer votre compte?", new_confirmation_path(resource_name)
  br

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Vous n'avez pas reçu les informations pour débloquer votre compte?", new_unlock_path(resource_name)
  br

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Me connecter avec #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br